---
title: "Comparisons"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{comparisons}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>", 
  fig.align = "center",
  eval = TRUE
)
```

```{r setup}
library(zazou)
library(ape)
set.seed(42)
```

# Parameters

```{r parameters}
tree <- read.tree(text = "(((A:1,B:1):1,C:2):1,(D:1,E:1):2);")
true_shifts <- c(0, -3, 0, 0, 0, 0, -2, 0)
alpha <- 1
lambda <- 0.1
```

```{r}
(true_zscores <- incidence_matrix(tree) %*% true_shifts)
```


# Simulations

```{r simulations}
observed_zscores <- simu_zscores(tree = tree, shifts = true_shifts, 
                                 alpha = 1, graph = TRUE)
observed_zscores
```


# Comparisons

## L-BFGS-B algorithm

```{r lbfgsb}
mthd1 <- estimate_shifts(Delta0 = rep(0, 8), zscores = observed_zscores, 
                         lambda = lambda, tree = tree, alpha = alpha, 
                         method = "L-BFGS-B")
mthd1
plot(mthd1)
```

## Shooting algorithm


```{r shooting}
mthd2 <- estimate_shifts(Delta0 = rep(0, 8), zscores = observed_zscores, 
                         lambda = lambda, tree = tree, alpha = alpha, 
                         method = "shooting")
mthd2
plot(mthd2)
```


## Results

### Shifts

```{r shifts}
true_shifts
mthd1$shift_est
mthd2$shift_est
```

### Z-scores

```{r zsc}
t(true_zscores)
mthd1$zscores_est
mthd2$zscores_est
```

### Objective 

```{r obj}
mthd1$objective_value
mthd2$objective_value
```

### Other informations

```{r other}
mthd1$optim_info
mthd2$optim_info
```

