on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

name: R-CMD-check-dev

jobs:
  R-CMD-check:
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-16.04

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
